Revert "Merge branch 'master' into DX-1404"
This reverts commit 7f93161cf5b58296d8db0f326a3038030185b07a, reversing
changes made to e184e173e0d9ebe1513e77bc240dc9e75b0200fe.

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -9,21 +9,25 @@ exerr() {
 state run lint-staged
 exerr $? "Linting of staged files has failed"
 
-# Detect unformatted files.
-gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '.go$' | grep -vE '^vendor/')
-[ -z "$gofiles" ] && exit 0
+# Copyright 2012 The Go Authors. All rights reserved.
+# Use of this source code is governed by a BSD-style
+# license that can be found in the LICENSE file.
+
+# git gofmt pre-commit hook
+#
+# To use, store as .git/hooks/pre-commit inside your repository and make sure
+# it has execute permissions.
+#
+# This script does not handle file names that contain spaces.
 
 unformatted=$(gofmt -l $gofiles)
 [ -z "$unformatted" ] && exit 0
 
-# Format them.
-gofmt -w $unformatted
-exerr $? "Formatting of staged files has failed"
+# Some files are not gofmt'd. Print message and fail.
 
-# Notify the user of formatted files and fail.
-echo >&2 "The following files have been reformatted. Please verify and/or re-stage changes before attempting to commit again."
-for file in $unformatted; do
-  echo >&2 "  $PWD/$file"
+echo >&2 "Go files must be formatted with gofmt. Please run:"
+for fn in $unformatted; do
+  echo >&2 "  gofmt -w $PWD/$fn"
 done
 
 exit 1
