Update Go to 1.20 in gha workflow, update asy deps install

diff --git a/activestate.yaml b/activestate.yaml
--- a/activestate.yaml
+++ b/activestate.yaml
@@ -47,14 +47,29 @@ constants:
 scripts:
   - name: install-deps
     language: bash
+    if: ne .Shell "cmd"
     value: |
-      export GO111MODULE=on
-      goflags="${GOFLAGS}"; unset GOFLAGS
-      GOFLAGS="${goflags}"
-      pushd ~
-      go install github.com/ActiveState/gozip/cmd/gozip@e455986
-      popd
-      $scripts.install-deps-os
+      if ! type "go" &> /dev/null; then
+        echo "go is not installed. Please install Go version 1.11 or above."
+        exit 1
+      fi
+      if ! type "golangci-lint" &> /dev/null; then
+        echo "golangci-lint was not found on your PATH, installing .."
+        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.51.2
+      fi
+      git config core.hooksPath .githooks
+      if ! type "swagger" &> /dev/null; then
+        echo "swagger was not found on your PATH, installing .."
+        go install github.com/go-swagger/go-swagger/cmd/swagger@v0.27.0
+      fi
+      if ! type "actionlint" &> /dev/null; then
+        echo "actionlint was not found on your PATH, installing .."
+        go install github.com/rhysd/actionlint/cmd/actionlint@v1.6.23
+      fi
+      if ! type "gozip" &> /dev/null; then
+        echo "gozip was not found on your PATH, installing .."
+        go install github.com/ActiveState/gozip/cmd/gozip@e455986
+      fi
   - name: install-deps-os
     language: bash
     if: ne .OS.Name "Linux"
@@ -387,23 +402,7 @@ events:
   - name: activate
     if: ne .Shell "cmd"
     value: |
-      if ! type "go" &> /dev/null; then
-        echo "go is not installed. Please install Go version 1.11 or above."
-        exit 1
-      fi
-      if ! type "golangci-lint" &> /dev/null; then
-        echo "golangci-lint was not found on your PATH, installing .."
-        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0
-      fi
-      git config core.hooksPath .githooks
-      if ! type "swagger" &> /dev/null; then
-        echo "swagger was not found on your PATH, installing .."
-        go install github.com/go-swagger/go-swagger/cmd/swagger@v0.27.0
-      fi
-      if ! type "actionlint" &> /dev/null; then
-        echo "actionlint was not found on your PATH, installing .."
-        go install github.com/rhysd/actionlint/cmd/actionlint@v1.6.22
-      fi
+      $scripts.install-deps
   - name: file-changed
     scope: ["internal/locale/locales"]
     value: build
