Daemon implementation

diff --git a/activestate.yaml b/activestate.yaml
--- a/activestate.yaml
+++ b/activestate.yaml
@@ -10,6 +10,9 @@ constants:
   - name: BUILD_TARGET_32BIT
     if: ne .OS.Name "Windows"
     value: ./build/state32
+  - name: BUILD_DAEMON_TARGET
+    if: ne .OS.Name "Windows"
+    value: ./build/state-svc
   - name: SET_ENV
     description: The environment settings used throughout our project
     value: |
@@ -21,17 +24,42 @@ constants:
         GO_BUILD_TAGS="CI"
       fi
 scripts:
-  - name: preprocess
+  - name: install-deps
     language: bash
-    description: Generates assets required by the project that aren't just specific to the build
     value: |
-      set -e
+      pushd ~
+      if ! type "protoc" &> /dev/null; then
+       echo "protoc was not found on your PATH, installing .."
+       if type "brew" &> /dev/null; then
+         brew install protobuf
+       elif type "apt" &> /dev/null; then
+         apt install -y protobuf-compiler
+       else
+         echo "Please install the protobuf compiler (protoc): https://grpc.io/docs/protoc-installation/"
+         exit 1
+       fi
+      fi
+      if ! type "protoc-gen-go" &> /dev/null; then
+       echo "installing protoc-gen-go"
+       go get google.golang.org/protobuf/cmd/protoc-gen-go
+      fi
+      if ! type "protoc-gen-go-grpc" &> /dev/null; then
+       echo "installing protoc-gen-go-grpc"
+       go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
+      fi
+      popd
       if ! type "packr" &> /dev/null; then
         echo "packr was not found on your PATH, installing .."
         pushd ~
         go get -u github.com/gobuffalo/packr/...
         popd
       fi
+  - name: preprocess
+    language: bash
+    description: Generates assets required by the project that aren't just specific to the build
+    value: |
+      set -e
+      $scripts.install-deps
       $constants.SET_ENV
       packr
       go run scripts/constants-generator/main.go -- internal/constants/generated.go
@@ -64,6 +92,12 @@ scripts:
       export GOOS=${1}
       [ -z "${2}" ] && >&2 echo "must provide output file as 2nd arg" && exit 1
       go build -tags "internal $GO_BUILD_TAGS" -o ${2} $constants.CLI_BUILDFLAGS $constants.CLI_PKGS
+  - name: build-svc
+    language: bash
+    description: Builds the state-svc daemon
+    value: |
+      set -e
+      go build -o $constants.BUILD_DAEMON_TARGET ./cmd/state-svc
   - name: install
     language: bash
     description: Installs the current HEAD version into GOBIN
