Install golangci on activate instead of preprocess (bypass CI issue)

diff --git a/activestate.yaml b/activestate.yaml
--- a/activestate.yaml
+++ b/activestate.yaml
@@ -62,10 +62,6 @@ scripts:
         echo "packr was not found on your PATH, installing .."
         go install github.com/gobuffalo/packr/packr@v1.30.1
       fi
-      if ! type "golangci-lint" &> /dev/null; then
-        echo "golangci-lint was not found on your PATH, installing .."
-        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0
-      fi
       GOFLAGS="${goflags}"
       $scripts.install-deps-os
   - name: install-deps-os
@@ -369,6 +365,10 @@ events:
       if ! type "go" &> /dev/null; then
         echo "go is not installed. Please install Go version 1.11 or above."
         exit 1
+      fi
+      if ! type "golangci-lint" &> /dev/null; then
+        echo "golangci-lint was not found on your PATH, installing .."
+        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0
       fi
       git config core.hooksPath .githooks
       if ! type "swagger" &> /dev/null; then
