Remote installer should be deployed to its own branch.

diff --git a/activestate.yaml b/activestate.yaml
--- a/activestate.yaml
+++ b/activestate.yaml
@@ -138,9 +138,26 @@ scripts:
         TARGET="${BUILD_REMOTE_INSTALLER_TARGET}.exe"
       fi
       GOFLAGS="" go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest
+
+      if [ "$GITHUB_HEAD_REF" != "" ]; then
+        BRANCH=${GITHUB_HEAD_REF}
+      elif [ "$GITHUB_REF" != "" ]; then
+        BRANCH=$(echo $GITHUB_REF | awk -F'/' '{print $NF}')
+      else
+        BRANCH=$(git rev-parse --abbrev-ref HEAD)
+      fi
+
+      if [ "$BRANCH" == "" ]; then
+        echo "Branch cannot be empty"
+        exit 1
+      fi
+      if [ "$BRANCH" == "release" ]; then
+        BRANCH=""
+      fi
+
       cd cmd/state-remote-installer
       go generate
-      go build -tags "$GO_BUILD_TAGS" -o ../../$BUILD_TARGET_DIR/$TARGET .
+      go build -tags "$GO_BUILD_TAGS" -o ../../$BUILD_TARGET_DIR/$BRANCH/$TARGET .
   - name: install
     language: bash
     description: Installs the current HEAD version into GOBIN
