Add script for format checking

diff --git a/activestate.yaml b/activestate.yaml
--- a/activestate.yaml
+++ b/activestate.yaml
@@ -360,6 +360,39 @@ scripts:
     value: |
       golangci-lint run --no-config
       actionlint
+  - name: check-format
+    language: bash
+    description: "Checks if the code is formatted correctly"
+    value: |
+      set -e
+      if [ "$GITHUB_HEAD_REF" != "" ]; then
+        BRANCH=${GITHUB_HEAD_REF}
+      elif [ "$GITHUB_REF" != "" ]; then
+        BRANCH=$(echo $GITHUB_REF | awk -F'/' '{print $NF}')
+      else
+        BRANCH=$(git rev-parse --abbrev-ref HEAD)
+      fi
+
+      git fetch origin $BRANCH:refs/remotes/origin/$BRANCH
+
+      changed_files=$(git diff --name-only origin/$BRANCH)
+
+      missing_newline_at_eof=0
+      for file in $changed_files; do
+          if file "$file" | grep -q 'text|ASCII'; then
+              if [ "$(tail -c 1 "$FILE")" != "" ]; then
+                  echo "Missing newline at end of file: $file"
+                  missing_newline_at_eof=1
+              fi
+          fi
+      done
+
+      if [ "$missing_newline_at_eof" -ne 0 ]; then
+          echo "Error: Some text files are missing a newline at the end."
+          exit 1
+      else
+          echo "Success: All text files end with a newline."
+      fi
   - name: grab-mergecommits
     language: bash
     value: |
