Merge separate integration test steps into a single one with conditionals.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -202,20 +202,22 @@ jobs:
 
       - # === Deploy for Integration Tests # NEVER run this against production branches. This is meant for PR deployments. ===
         name: Deploy for Integration Tests # NEVER run this against production branches. This is meant for PR deployments.
-        if: github.ref != 'refs/heads/release' && github.ref != 'refs/heads/master'
+        if: github.ref != 'refs/heads/release'
         shell: bash
         run: |
-          set +e
-          LABELS="${{ join(github.event.pull_request.labels.*.name, ',') }}"
-          LABELCHECK="$(echo $LABELS | grep "Test:")" # This line is causing a non-zero exit if `set -e` is set, and I can't figure out why
-          TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
-          set -e
-          echo "Labels: $LABELS"
-          echo "Target Branch: $TARGET_BRANCH"
+          if [ "$GITHUB_EVENT_NAME" != "schedule" ]; then
+            set +e
+            LABELS="${{ join(github.event.pull_request.labels.*.name, ',') }}"
+            LABELCHECK="$(echo $LABELS | grep "Test:")" # This line is causing a non-zero exit if `set -e` is set, and I can't figure out why
+            TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
+            set -e
+            echo "Labels: $LABELS"
+            echo "Target Branch: $TARGET_BRANCH"
 
-          if [ "$LABELCHECK" == "" ] && [ "$TARGET_BRANCH" != "beta" ] && [ "$TARGET_BRANCH" != "release" ]; then
-            echo "Not running because no test labels were set nor beta or release were targeted."
-            exit 0
+            if [ "$LABELCHECK" == "" ] && [ "$TARGET_BRANCH" != "beta" ] && [ "$TARGET_BRANCH" != "release" ]; then
+              echo "Not running because no test labels were set nor beta or release were targeted."
+              exit 0
+            fi
           fi
 
           state run deploy-updates
@@ -224,40 +226,34 @@ jobs:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
-      - # === Deploy for Nightly Integration Tests ===
-        name: Deploy for Nightly Integration Tests
-        if: github.event_name == 'schedule'
-        shell: bash
-        run: |
-          state run deploy-updates
-          state run deploy-installers
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-
       - # === Integration Tests ===
         name: Integration Tests
-        if: github.ref != 'refs/heads/release' && github.ref != 'refs/heads/master'
+        id: integration_tests
+        if: github.ref != 'refs/heads/release'
         shell: bash
         run: |
-          LABELS="${{ join(github.event.pull_request.labels.*.name, ',') }}"
-          IFS=',' read -r -a TESTS <<< "$LABELS"
-          TEST_SUITE_TAGS=""
-          for i in "${TESTS[@]}"; do
-            START=${i%:*}
-            if [ "$START" == "Test" ]; then
-              TAG=${i##*:}
-              TAG=$(echo $TAG | xargs)
-              TEST_SUITE_TAGS="$TAG:$TEST_SUITE_TAGS"
+          if [ "$GITHUB_EVENT_NAME" != "schedule" ]; then
+            LABELS="${{ join(github.event.pull_request.labels.*.name, ',') }}"
+            IFS=',' read -r -a TESTS <<< "$LABELS"
+            TEST_SUITE_TAGS=""
+            for i in "${TESTS[@]}"; do
+              START=${i%:*}
+              if [ "$START" == "Test" ]; then
+                TAG=${i##*:}
+                TAG=$(echo $TAG | xargs)
+                TEST_SUITE_TAGS="$TAG:$TEST_SUITE_TAGS"
+              fi
+            done
+
+            TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
+            echo "Target branch: $TARGET_BRANCH"
+
+            if [ "$TEST_SUITE_TAGS" == "" ] && [ "$TARGET_BRANCH" != "beta" ] && [ "$TARGET_BRANCH" != "release" ]; then
+              echo "Not running because no test labels were set nor beta or release were targeted."
+              exit 0
             fi
-          done
-
-          TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
-          echo "Target branch: $TARGET_BRANCH"
-
-          if [ "$TEST_SUITE_TAGS" == "" ] && [ "$TARGET_BRANCH" != "beta" ] && [ "$TARGET_BRANCH" != "release" ]; then
-            echo "Not running because no test labels were set nor beta or release were targeted."
-            exit 0
+          else
+            TEST_SUITE_TAGS="all"
           fi
 
           echo "Running integration tests with tags: $TEST_SUITE_TAGS (empty means every test not specifically tagged)"
@@ -272,28 +268,7 @@ jobs:
           CODE=$?
           cat build/integration-tests.out | gotestfmt
           exit $CODE
-        env:
-          INTEGRATION_TEST_USERNAME: ${{ secrets.INTEGRATION_TEST_USERNAME }}
-          INTEGRATION_TEST_PASSWORD: ${{ secrets.INTEGRATION_TEST_PASSWORD }}
-          INTEGRATION_TEST_TOKEN: ${{ secrets.INTEGRATION_TEST_TOKEN }}
-          PLATFORM_API_TOKEN: ${{ secrets.PLATFORM_API_TOKEN }}
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-
-      - # === Nightly Integration Tests ===
-        name: Nightly Integration Tests
-        id: nightly_integration_tests
-        if: github.event_name == 'schedule'
-        timeout-minutes: 90
-        shell: bash
-        run: |
-          export TEST_SUITE_TAGS="all"
-          set +e
-          SHELL='' go test -timeout 90m -v `go list ./... | grep integration` &> build/integration-tests.out
-          CODE=$?
-          cat build/integration-tests.out | gotestfmt
-          exit $CODE
-        continue-on-error: true
+        continue-on-error: ${{ github.event_name == 'schedule' }}
         env:
           INTEGRATION_TEST_USERNAME: ${{ secrets.INTEGRATION_TEST_USERNAME }}
           INTEGRATION_TEST_PASSWORD: ${{ secrets.INTEGRATION_TEST_PASSWORD }}
@@ -304,7 +279,7 @@ jobs:
 
       - # === Notify Slack of Nightly Integration Test Failures ===
         name: Notify Slack of Nightly Integration Test Failures
-        if: github.event_name == 'schedule' && steps.nightly_integration_tests.outcome == 'failure'
+        if: github.event_name == 'schedule' && steps.integration_tests.outcome == 'failure'
         uses: slackapi/slack-github-action@v1.18.0
         with:
           payload: |
@@ -329,7 +304,7 @@ jobs:
                   "type": "section",
                   "text": {
                     "type": "plain_text",
-                    "text": "Select the '${{ matrix.platform }}' job and expand 'Nightly Integration Tests' to inspect the failures."
+                    "text": "Select the '${{ matrix.platform }}' job and expand 'Integration Tests' to inspect the failures."
                   }
                 }
               ]
