Only deploy as latest when label is set

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -197,7 +197,18 @@ jobs:
       - # === Generate Update ===
         name: Generate Update
         shell: bash
-        run: state run generate-update
+        run: |
+          set +e
+          LABELS="${{ join(github.event.pull_request.labels.*.name, ',') }}"
+          LABELCHECK="$(echo $LABELS | grep "Deploy: latest")" # This line is causing a non-zero exit if `set -e` is set, and I can't figure out why
+          set -e
+
+          if [ "$LABELCHECK" == "" ]; then
+            state run generate-update
+          else
+            echo "Generating update for latest release"
+            state run generate-update --latest
+          fi
 
       - # === Deploy for Integration Tests # NEVER run this against production branches. This is meant for PR deployments. ===
         name: Deploy for Integration Tests # NEVER run this against production branches. This is meant for PR deployments.
